version: '2.4'

services:
  iota:
    build:
      context: app
    image: iota-demo
    container_name: iota-demo
    environment:
      IOTA_NODE: "https://potato.iotasalad.org:14265"
      REDIS_HOST: redis
      VALUE_PER_TEN_SECONDS: 1
    command: ["$ADDRESS"]
  mosquitto:
    build:
      context: mosquitto
    image: mosquitto-auth-plug
    container_name: mosquitto
    ports:
      - "1883"
    depends_on:
      - redis
  redis-bootstrap:
    image: redis-bootstrap
    build:
      context: redis
    container_name: redis-bootstrap
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: redis
